In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler

import warnings
warnings.filterwarnings('ignore')

sns.set()
plt.style.use('ggplot')
%matplotlib inline

In [ ]:
heart_df = pd.read_csv('/content/drive/MyDrive/heart.csv')

In [ ]:
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [ ]:
heart_df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,1025.000000,1025.000000,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000
mean,54.434146,0.695610,0.942439,131.611707,246.00000,0.149268,0.529756,149.114146,0.336585,1.071512,1.385366,0.754146,2.323902,0.513171
std,9.072290,0.460373,1.029641,17.516718,51.59251,0.356527,0.527878,23.005724,0.472772,1.175053,0.617755,1.030798,0.620660,0.500070
min,29.000000,0.000000,0.000000,94.000000,126.00000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,0.000000,120.000000,211.00000,0.000000,0.000000,132.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,56.000000,1.000000,1.000000,130.000000,240.00000,0.000000,1.000000,152.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.00000,0.000000,1.000000,166.000000,1.000000,1.800000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.00000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [ ]:
heart_df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [ ]:
heart_df.head(50)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
5,58,0,0,100,248,0,0,122,0,1.0,1,0,2,1
6,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0
7,55,1,0,160,289,0,0,145,1,0.8,1,1,3,0
8,46,1,0,120,249,0,0,144,0,0.8,2,0,3,0
9,54,1,0,122,286,0,0,116,1,3.2,1,2,2,0
10,71,0,0,112,149,0,1,125,0,1.6,1,0,2,1
11,43,0,0,132,341,1,0,136,1,3.0,1,0,3,0
12,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1
13,51,1,0,140,298,0,1,122,1,4.2,1,3,3,0
14,52,1,0,128,204,1,1,156,1,1.0,1,0,0,0
15,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1
16,51,0,2,140,308,0,0,142,0,1.5,2,1,2,1
17,54,1,0,124,266,0,0,109,1,2.2,1,1,3,0
18,50,0,1,120,244,0,1,162,0,1.1,2,0,2,1
19,58,1,2,140,211,1,0,165,0,0.0,2,0,2,1
20,60,1,2,140,185,0,0,155,0,3.0,1,0,2,0
21,67,0,0,106,223,0,1,142,0,0.3,2,2,2,1
22,45,1,0,104,208,0,0,148,1,3.0,1,0,2,1
23,63,0,2,135,252,0,0,172,0,0.0,2,0,2,1
24,42,0,2,120,209,0,1,173,0,0.0,1,0,2,1
25,61,0,0,145,307,0,0,146,1,1.0,1,0,3,0
26,44,1,2,130,233,0,1,179,1,0.4,2,0,2,1
27,58,0,1,136,319,1,0,152,0,0.0,2,2,2,0
28,56,1,2,130,256,1,0,142,1,0.6,1,1,1,0
29,55,0,0,180,327,0,2,117,1,3.4,1,0,2,0
30,44,1,0,120,169,0,1,144,1,2.8,0,0,1,0
31,50,0,1,120,244,0,1,162,0,1.1,2,0,2,1
32,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
33,70,1,2,160,269,0,1,112,1,2.9,1,1,3,0
34,50,1,2,129,196,0,1,163,0,0.0,2,0,2,1
35,46,1,2,150,231,0,1,147,0,3.6,1,0,2,0
36,51,1,3,125,213,0,0,125,1,1.4,2,1,2,1
37,59,1,0,138,271,0,0,182,0,0.0,2,0,2,1
38,64,1,0,128,263,0,1,105,1,0.2,1,1,3,1
39,57,1,2,128,229,0,0,150,0,0.4,1,1,3,0
40,65,0,2,160,360,0,0,151,0,0.8,2,0,2,1
41,54,1,2,120,258,0,0,147,0,0.4,1,0,3,1
42,61,0,0,130,330,0,0,169,0,0.0,2,0,2,0
43,46,1,0,120,249,0,0,144,0,0.8,2,0,3,0
44,55,0,1,132,342,0,1,166,0,1.2,2,0,2,1
45,42,1,0,140,226,0,1,178,0,0.0,2,0,2,1
46,41,1,1,135,203,0,1,132,0,0.0,1,0,1,1
47,66,0,0,178,228,1,1,165,1,1.0,1,2,3,0
48,66,0,2,146,278,0,0,152,0,0.0,1,1,2,1
49,60,1,0,117,230,1,1,160,1,1.4,2,2,3,0

In [ ]:
x=heart_df.drop('target',axis=1)
y=heart_df['target']

scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

random_forrest = RandomForestClassifier(criterion = 'gini', max_depth = 7, max_features = 'sqrt', min_samples_leaf = 2, min_samples_split = 4, n_estimators = 180)
random_forrest.fit(x_train, y_train)

y_pred = random_forrest.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy of the model",accuracy_score(y_test,y_pred))
print("Confusion matrix of the model",confusion_matrix(y_test,y_pred))
print("Classification Report",classification_report(y_test,y_pred))

Accuracy of the model 0.9512987012987013
Confusion matrix of the model [[150   9]
 [  6 143]]
Classification Report               precision    recall  f1-score   support

           0       0.96      0.94      0.95       159
           1       0.94      0.96      0.95       149

    accuracy                           0.95       308
   macro avg       0.95      0.95      0.95       308
weighted avg       0.95      0.95      0.95       308

In [ ]:
import pickle
model = random_forrest
pickle.dump(model, open("heart.pkl",'wb'))